// app/api/report/route.ts
// API endpoint for generating PDF reports

import { NextRequest, NextResponse } from "next/server";
import jsPDF from "jspdf";

export async function GET(request: NextRequest) {
  try {
    const assessmentId = request.nextUrl.searchParams.get("id");

    if (!assessmentId) {
      return NextResponse.json(
        { success: false, message: "Assessment ID is required" },
        { status: 400 }
      );
    }

    // Generate PDF
    const pdf = new jsPDF();
    
    // Title
    pdf.setFontSize(20);
    pdf.text("ECLIPS Assessment Report", 20, 20);
    
    // Company info
    pdf.setFontSize(12);
    pdf.text(`Assessment ID: ${assessmentId}`, 20, 40);
    pdf.text(`Company: Elcon Engineers Pvt. Ltd.`, 20, 50);
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 60);
    
    // Decision
    pdf.setFontSize(14);
    pdf.setTextColor(16, 185, 129);
    pdf.text("✓ APPROVED", 20, 80);
    
    pdf.setTextColor(0, 0, 0);
    pdf.setFontSize(11);
    pdf.text(`Risk Score: 72/100`, 20, 95);
    pdf.text(`Confidence: 85%`, 20, 105);
    pdf.text(`Data Quality: 78%`, 20, 115);
    
    // Credit Recommendation
    pdf.setFontSize(12);
    pdf.text("Credit Recommendation", 20, 140);
    pdf.setFontSize(11);
    pdf.text(`Credit Limit: ₹50,00,000 INR`, 20, 155);
    pdf.text(`Payment Terms: Net 30 days`, 20, 165);
    
    // Strengths
    pdf.setFontSize(12);
    pdf.text("Key Strengths", 20, 190);
    pdf.setFontSize(10);
    pdf.text("• Strong financial position with consistent revenue growth", 25, 200);
    pdf.text("• Good market reputation in engineering sector", 25, 210);
    pdf.text("• Established operational track record since 2015", 25, 220);
    
    // Risks
    pdf.setFontSize(12);
    pdf.text("Key Risks", 20, 240);
    pdf.setFontSize(10);
    pdf.text("• Moderate exposure to construction sector volatility", 25, 250);
    pdf.text("• Limited international diversification", 25, 260);
    
    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text("This report is generated by ECLIPS - Confidential", 20, 280);
    
    // Get PDF as bytes
    const pdfBytes = pdf.output("arraybuffer");
    const buffer = Buffer.from(pdfBytes);

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="ECLIPS-Report-${assessmentId}.pdf"`,
        "Content-Length": buffer.length.toString(),
      },
    });
  } catch (error) {
    console.error("[REPORT API] Error:", error);
    return NextResponse.json(
      {
        success: false,
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
